### ISSUE TITLE
Theme doesnt works with latest Atom

### ISSUE THREAD

**Issue by themakerman** [odahcam/atom-sublime-monokai-syntax#4]
![image](https://user-images.githubusercontent.com/14818804/29117861-64fab048-7d32-11e7-9544-1ca31ecfe619.png)

No syntax coloring. Everything is just plain white.

**Comment by odahcam** [comment]
My 1.18.0 Atom looks fine, I'm waiting for updates.

**Comment by odahcam** [comment]
Closing because there's no enough information to work in.
